version: '3.8'
services:
  bouncer-unifi:
    image: ghcr.io/teifun2/cs-unifi-bouncer:latest
    container_name: bouncer-unifi
    environment:
      CROWDSEC_BOUNCER_API_KEY: MyApiKey
      CROWDSEC_URL: "http://crowdsec:8080/"
      UNIFI_HOST: "x.x.x.x:8728"
      UNIFI_USER: "api"
      UNIFI_PASS: "password"
    restart: unless-stopped


